POST http://localhost:3000/api/properties
Content-Type: application/json
X-Origin: getincouch.vercel.app

{
  "title": "Piso en alquiler en calle María Inmaculada",
  "description": "Ideal para estudiantes. Situado justo en el campus Reina Merces. Cerca del centro comercial Lagoh y múltiples puntos de interés.",
  "price": 800,
  "street": "María Inmaculada",
  "city": "Mairena del Alcor",
  "country": "España",
  "zipCode": "41510",
  "propertyType": "Apartamento",
  "propertySize": 40,
  "numberOfBathrooms": 1,
  "numberOfBedrooms": 3,
  "furniture": "Amueblado",
  "parking": "Sin parking",
  "airConditioning": false,
  "heating": false,
  "owner": "63f1975aff912523d6589228"
}


###
GET http://localhost:3000/api/properties/

###
PUT http://localhost:3000/api/properties/6490834ccc028a2368b2e0e6
Content-Type: application/json

{
  "street": "María Inmaculada, 13A",
  "propertySize": 90,
  "propertyType": "Casa",
  "parking": "Sin parking",
  "price": 1300
}