POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "ismperort",
  "name": "Test name",
  "password": "test_passwd"
}


###
GET http://localhost:3000/api/users/

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "ismperort",
  "password": "Ism&19032001"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "anotherUser",
  "password": "123123123Ism&"
}